apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-alpine
    tag: alpine
  name: nginx-alpine
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      app: nginx-alpine
      tag: alpine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-alpine
        tag: alpine
    spec:
      containers:
      - image: {{ .Values.image.name }:{{ .Values.image.tag }}
        imagePullPolicy: { Values.image.pullPolicy }
        name: nginx-alpine
        resources:
{{ toYaml .Values.resources | indent 12 }}
